# Generated by Django 5.0.4 on 2024-06-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='wo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
