# Generated by Django 5.0.4 on 2024-06-20 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expense_wo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='wo',
        ),
    ]
