# Generated by Django 5.0.4 on 2024-06-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='wo',
            field=models.IntegerField(default=0),
        ),
    ]
